src/Entity/Avis.php
<?php

namespace App\Entity;

use App\Repository\AvisRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AvisRepository::class)]
class Avis
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $DateAvis = null;

    #[ORM\Column]
    private ?int $Note = null;

    #[ORM\ManyToOne(inversedBy: 'avis')]
    private ?MarketPlace $MarketPlace = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateAvis(): ?\DateTimeInterface
    {
        return $this->DateAvis;
    }

    public function setDateAvis(\DateTimeInterface $DateAvis): static
    {
        $this->DateAvis = $DateAvis;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->Note;
    }

    public function setNote(int $Note): static
    {
        $this->Note = $Note;

        return $this;
    }

    public function getMarketPlace(): ?MarketPlace
    {
        return $this->MarketPlace;
    }

    public function setMarketPlace(?MarketPlace $MarketPlace): static
    {
        $this->MarketPlace = $MarketPlace;

        return $this;
    }
}

src/Controller/AdmindashController.php
<?php

namespace App\Controller;

use App\Form\AvisType;
use App\Form\EquipeType;
use App\Form\SheetsType;
use App\Repository\AvisjoueurRepository;
use App\Repository\EquipeRepository;
use App\Repository\UserRepository;
use CMEN\GoogleChartsBundle\GoogleCharts\Charts\BarChart;
use CMEN\GoogleChartsBundle\GoogleCharts\Charts\PieChart;
use Doctrine\Persistence\ManagerRegistry;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Csv;
use PhpOffice\PhpSpreadsheet\Writer\Ods;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\UX\Chartjs\Builder\ChartBuilderInterface;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Font;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;


/*
   *
   *
   * @author : ghazi saoudi
   *
   *
   *
   */



#[Route('/admin')]
class AdmindashController extends AbstractController
{
    #[Route('/admindash', name: 'admindash')]
    public function index(): Response
    {
        return $this->render('admindash/index.html.twig');
    }



    #[Route('/list', name: 'list')]
    public function list(Request $request, EquipeRepository $equipeRepository): Response
    {
        $year = $request->query->get('year');
        $order = $request->query->get('order');


        if ($year) {
            $donnees = $equipeRepository->findByYear($year); // Implement this method in your repository
        } else {
            $donnees = $equipeRepository->findAll();
        }
        if ($order === 'AtoZ') {
            $donnees = $equipeRepository->orderByname();
        } elseif ($order === 'date') {
            $donnees = $equipeRepository->orderBydate();
        }

        return $this->render('admindash/ListTeam.html.twig', ['donnees' => $donnees]);
    }




    #[Route('/listA', name: 'listA')]
    public function listAvis(AvisjoueurRepository $avisjoueurRepository,Request $request): Response
    {
        $query = $request->query->get('query');
        $donnees = $avisjoueurRepository->findBySearchQuery($query);
        return $this->render('admindash/ListAvis.html.twig',['donnees' => $donnees]);
    }




    #[Route('/suppE/{i}', name: 'suppE')]
    public function delete(EquipeRepository $repository ,$i,ManagerRegistry $doctrine): Response
    {
        // recuperer l'auteur a supp
        $equipe = $repository->find($i);
        // action de suppresuion
        $em=$doctrine->getManager();
        $em->remove($equipe);
        $em->flush();


        return $this->redirectToRoute('list');
    }


    #[Route('/suppA/{i}', name: 'suppA')]
    public function deleteAvis(AvisjoueurRepository $repository ,$i,ManagerRegistry $doctrine): Response
    {
        // recuperer l'auteur a supp
        $avis = $repository->find($i);
        // action de suppresuion
        $em=$doctrine->getManager();
        $em->remove($avis);
        $em->flush();


        return $this->redirectToRoute('listA');
    }

    #[Route('/edit_equipe/{id}', name: 'edit_equipe')]
    public function editEquipe(Request $request, $id,ManagerRegistry $doctrine,EquipeRepository $rep): Response
    {

        $var=$rep->find($id);

        $equipe=$var;

        $em =$doctrine->getManager();




        $form = $this->createForm(EquipeType::class, $equipe);

        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {

            $em->flush();


            return $this->redirectToRoute('list');
        }

        return $this->render('admindash/EditEquipe.html.twig', [
            'form' => $form->createView(),
        ]);
    }
    #[Route('/edit_avis/{id}', name: 'edit_avis')]
    public function editAvis(Request $request, $id,ManagerRegistry $doctrine,AvisjoueurRepository $rep): Response
    {

        $var=$rep->find($id);

        $avis=$var;

        $em =$doctrine->getManager();




        $form = $this->createForm(AvisType::class, $avis);

        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {

            $em->flush();


            return $this->redirectToRoute('listA');
        }

        return $this->render('admindash/EditAvis.html.twig', [
            'form' => $form->createView(),
        ]);
    }

//------------------------------stats-----------------

    #[Route('/stats', name: 'statsique')]
    public function combinedStatsAndChart(EquipeRepository $equipeRepository, AvisjoueurRepository $avisjoueurRepository, UserRepository $userRepository, ChartBuilderInterface $chartBuilder): Response {
        // Fetch data for statistics
        $equipe = $equipeRepository->Nbrequipe();
        $user = $userRepository->Nbruser();
        $avis = $avisjoueurRepository->Nbravis();

        // Fetch data for pie chart
        $results = $avisjoueurRepository->countAvisByJoueur();

        $res = $equipeRepository->countTeamsByYear();

        // Prepare data for the chart
        $data = [['Joueur', 'Nombre d\'avis']];
        foreach ($results as $result) {
            $data[] = [$result['firstname'], $result['totalAvis']];
        }

        $res = $equipeRepository->countTeamsByYear();
        $dataForBarChart = [['Year', 'Number of Teams']];
        foreach ($res as $item) {
            $dataForBarChart[] = [$item['year'], $item['teamCount']];
        }


        // Create PieChart instance
        $pieChart = new PieChart();

        // Set data to the chart
        $pieChart->getData()->setArrayToDataTable($data);

        // Set chart options
        $pieChart->getOptions()->setTitle('Nombre des Avis par joueur');
        $pieChart->getOptions()->setHeight(900);
        $pieChart->getOptions()->setWidth(1400);
        $pieChart->getOptions()->getTitleTextStyle()->setBold(true);
        $pieChart->getOptions()->getTitleTextStyle()->setColor('#009900');
        $pieChart->getOptions()->getTitleTextStyle()->setItalic(true);
        $pieChart->getOptions()->getTitleTextStyle()->setFontName('Arial');
        $pieChart->getOptions()->getTitleTextStyle()->setFontSize(20);




        $barChart = new BarChart();

        // Set data to the chart
        $barChart->getData()->setArrayToDataTable($dataForBarChart);

        // Set chart options
        $barChart->getOptions()->setTitle('Nombre des equipe par année');
        $barChart->getOptions()->setHeight(800);
        $barChart->getOptions()->setWidth(1300);
        $barChart->getOptions()->getTitleTextStyle()->setBold(true);
        $barChart->getOptions()->getTitleTextStyle()->setColor('#009900');
        $barChart->getOptions()->getTitleTextStyle()->setItalic(true);
        $barChart->getOptions()->getTitleTextStyle()->setFontName('Arial');
        $barChart->getOptions()->getTitleTextStyle()->setFontSize(20);

        // Render the view with the statistics and the chart
        return $this->render('admindash/stats.html.twig', [
            'equipe' => $equipe,
            'user' => $user,
            'avis' => $avis,
            'piechart' => $pieChart,
            'barchart' => $barChart
        ]);
    }





    //------------excel-------------



    protected function createSpreadsheet(EquipeRepository $equipeRepository)
    {
        $spreadsheet = new Spreadsheet();
        // Get active sheet - it is also possible to retrieve a specific sheet
        $sheet = $spreadsheet->getActiveSheet();

        // Set cell name and merge cells
        $sheet->setCellValue('A1', 'Liste des Equipes')->mergeCells('A1:D1');

        // Set column names
        $columnNames = [
            'Nom de l\'équipe',
            'Date de création',
            'Logo',
        ];
        $columnLetter = 'A';
        foreach ($columnNames as $columnName) {
            // Center text
            $sheet->getStyle($columnLetter.'1')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            // Text in bold
            $sheet->getStyle($columnLetter.'1')->getFont()->setBold(true);
            // Set background color
            $sheet->getStyle($columnLetter.'1')->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FFA07A'); // Light Salmon
            // Set font color
            $sheet->getStyle($columnLetter.'1')->getFont()->getColor()->setARGB('FFFFFF'); // White
            // Border
            $sheet->getStyle($columnLetter.'1')->applyFromArray([
                'borders' => [
                    'allBorders' => [
                        'borderStyle' => Border::BORDER_THIN,
                        'color' => ['argb' => '000000'],
                    ],
                ],
            ]);
            // Autosize column
            $sheet->getColumnDimension($columnLetter)->setAutoSize(true);
            $columnLetter++;
        }

        // Fetch data from database
        $browserCharacteristics = $equipeRepository->findAll();

        // Add data for each row
        $i = 2; // Beginning row for active sheet
        foreach ($browserCharacteristics as $browserCharacteristic) {
            // Set cell values
            $sheet->setCellValue('A'.$i, $browserCharacteristic->getNom());
            $sheet->setCellValue('B'.$i, $browserCharacteristic->getDateCreation()->format('F j, Y'));

            // Insert logo (assuming the logo file path is stored in the database)
            $logoPath = $browserCharacteristic->getImage();
            if (!empty($logoPath) && file_exists($logoPath)) {
                $drawing = new Drawing();
                $drawing->setPath($logoPath);
                $drawing->setHeight(20); // Adjust height as needed
                $drawing->setWorksheet($sheet);
                $drawing->setCoordinates('C'.$i);
            }

            $i++;

templates/admindash/EditAvis.html.twig
{% extends 'admindash/index.html.twig' %}

{% block body %}
    <div style="padding-top: 100px">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header">Edit Equipe</div>

                        <div class="card-body">
                            {{ form_start(form, {'attr': {'class': 'form'}}) }}
                            <div class="form-group">
                                {{ form_label(form.user, 'player name', {'label_attr': {'class': 'control-label'}}) }}
                                {{ form_widget(form.user, {'attr': {'class': 'form-control', 'readonly': 'readonly'}}) }}
                            </div>

                            <div class="form-group">
                                {{ form_label(form.note, 'note', {'label_attr': {'class': 'control-label'}}) }}
                                {{ form_widget(form.note, {'attr': {'class': 'form-control', 'readonly': 'readonly'}}) }}
                            </div>
                            <div class="form-group">
                                {{ form_label(form.commentaire, 'commentaire', {'label_attr': {'class': 'control-label'}}) }}
                                {{ form_widget(form.commentaire, {'attr': {'class': 'form-control'}}) }}
                            </div>

                            <div class="form-group">
                                {{ form_label(form.dateavis, 'Date avis', {'label_attr': {'class': 'control-label'}}) }}
                                {{ form_widget(form.dateavis, {'attr': {'class': 'form-control'}}) }}
                            </div>
                            <div class="form-group" style="margin-left: 210px; margin-top: 20px">
                                {{ form_widget(form.submit, {'attr': {'class': 'btn btn-primary'}}) }}
                            </div>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/admindash/EditEquipe.html.twig
{% extends 'admindash/index.html.twig' %}

{% block body %}
    <div style="padding-top: 100px">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header">Edit Equipe</div>
                        <div class="card-body">
                            {{ form_start(form, {'attr': {'class': 'form'}}) }}
                            <div class="form-group">
                                {{ form_label(form.nom, 'Nom', {'label_attr': {'class': 'control-label'}}) }}
                                {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
                            </div>
                            <div class="form-group">
                                {{ form_label(form.image, 'Image', {'label_attr': {'class': 'control-label'}}) }}
                                <div class="custom-file">
                                    {{ form_widget(form.image, {'attr': {'class': 'custom-file-input', 'id': 'customFile'}}) }}
                                    <label class="custom-file-label" for="customFile"></label>
                                </div>
                            </div>
                            <div class="form-group">
                                {{ form_label(form.dateCreation, 'Date Creation', {'label_attr': {'class': 'control-label'}}) }}
                                {{ form_widget(form.dateCreation, {'attr': {'class': 'form-control'}}) }}
                            </div>
                            <div class="form-group" style="margin-left: 210px; margin-top: 20px">
                                {{ form_widget(form.submit, {'attr': {'class': 'btn btn-primary'}}) }}
                            </div>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/admindash/ListAvis.html.twig
{% extends 'admindash/index.html.twig' %}

{% block body %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

    <div style="padding-top: 100px">






        <div>
            <input required="" autocomplete="off" placeholder="search your items" id="search" type="text">
            <button id="click_to_record" class="btn btn-danger" style="border-radius: 200px"><i class="fa-solid fa-microphone"></i></button>
        </div>









        <h1 style="text-align: center">Liste des Avis</h1>
        <div style="overflow-x:auto;">
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th style="width: 10%;">ID</th>
                    <th style="width: 30%;">user</th>
                    <th style="width: 30%;">commentaire</th>
                    <th style="width: 30%;">date</th>
                    <th style="width: 30%;">note</th>
                    <th style="width: 30%;">Action</th>
                </tr>
                </thead>
                <tbody id="avisTableBody">
                {% for donnee in donnees %}
                    <tr>
                        <td>{{ donnee.idAvis }}</td>
                        <td>{{ donnee.user.firstname }}</td>
                        <td>{{ donnee.commentaire }}</td>
                        <td>{{ donnee.dateAvis|date('Y-m-d') }}</td>
                        <td>
                            {% for i in range(1, 6) %}
                                {% if i <= donnee.note %}
                                    <i class="fas fa-star"></i>
                                {% else %}
                                    <i class="far fa-star"></i>
                                {% endif %}
                            {% endfor %}
                        </td>
                        <td>
                            <form action="{{ path('suppA',{'i':donnee.idAvis}) }}">
                                <button class="btn btn-danger" style="margin-bottom: 10px">supprimer</button>
                            </form>
                            <form action="{{ path('edit_avis',{'id':donnee.idAvis}) }}">
                                <button class="btn btn-primary" style="padding-right: 30px;">modifier</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>












    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#search').keyup(function () {
                var query = $(this).val().toLowerCase(); // Convert query to lowercase for case-insensitive search
                $('#avisTableBody tr').each(function () {
                    var rowText = $(this).text().toLowerCase(); // Convert row text to lowercase
                    if (rowText.indexOf(query) === -1) {
                        $(this).hide(); // Hide row if it does not match the search query
                    } else {
                        $(this).show(); // Show row if it matches the search query
                    }
                });
            });
        });
    </script>





<style>
    input[type=text] {
        width: 15%;
        padding: 10px;
        border: 2px solid #ccc;

        margin-left: 8px;
        border-radius: 5px;
        transition: width 0.4s ease-in-out;
    }

    input[type=text] {
        transition: width 0.4s ease-in-out;
    }

    input[type=text]:focus {
        width: 25%;
    }




</style>



    <script>
        window.addEventListener('DOMContentLoaded', () => {
            const clickToRecord = document.getElementById("click_to_record");
            const searchInput = document.getElementById("search");
            let speech = true;

            if (!('webkitSpeechRecognition' in window)) {
                alert("Web Speech API is not supported by this browser!");
                return;
            }

            const recognition = new webkitSpeechRecognition();
            recognition.interimResults = true;

            recognition.addEventListener('result', e => {
                const transcript = Array.from(e.results)
                    .map(result => result[0])
                    .map(result => result.transcript)
                    .join('');

                searchInput.value = transcript;
                console.log(transcript);
            });

            clickToRecord.addEventListener('click', () => {
                if (speech) {
                    recognition.start();
                }
            });
        });
    </script>








{% endblock %}

templates/admindash/ListTeam.html.twig
{% extends 'admindash/index.html.twig' %}

{% block body %}

    <div style="padding-top: 100px">



        <a href="{{ path('export') }}" class="buttonDownload" style="margin-left: 1000px">Download</a>


        <div>
        <select name="cars" id="cars" class="form-select" style="width: 100px;  display: inline-block">
            <option value="">All</option>
            <option value="2020">2020</option>
            <option value="2021">2021</option>
            <option value="2022">2022</option>
            <option value="2024">2024</option>

        </select>

            <button id="applyButton" class="btn btn-primary"  style=" margin-left: 10px">filterBy</button>

            <select name="order" id="order" class="form-select" style="width: 120px; display: inline-block;margin-left: 30px;">
                <option value="">default</option>
                <option value="AtoZ">A-Z</option>
                <option value="date">Date added</option>


            </select>

            <button id="applyB" class="btn btn-primary" style=" margin-left: 10px" >ordeBy</button>
        </div>

        <h1 style="padding-top: 40px; text-align: center;">Liste des équipes</h1>
        <div style="overflow-x:auto;">
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th style="width: 10%;">ID</th>
                    <th style="width: 30%;">Nom</th>
                    <th style="width: 30%;">Image</th>
                    <th style="width: 30%;">Date</th>
                    <th style="width: 30%;">Action</th>
                </tr>
                </thead>
                <tbody>
                {% for donnee in donnees %}
                    <tr>
                        <td>{{ donnee.id }}</td>
                        <td>{{ donnee.nom }}</td>
                        <td><img src="/{{ donnee.image }}" style="align-content: center; width: 100px; height: 100px;"></td>
                        <td>{{ donnee.dateCreation|date('Y-m-d') }}</td>
                        <td> <form action="{{ path('suppE',{'i':donnee.id}) }}">
                                <button class="btn btn-danger"  style="margin-bottom: 10px">supprimer</button>

                            </form>

                            <form action="{{ path('edit_equipe',{'id':donnee.id}) }}">
                                <button class="btn btn-primary" style="padding-right: 30px;" > modifier</button>

                            </form>



                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>


    </div>

    <style>
        .buttonDownload {
            display: inline-block;
            position: relative;
            padding: 10px 25px;
            background-color: #4CC713;
            color: white;
            font-family: sans-serif;
            text-decoration: none;
            font-size: 0.9em;
            text-align: center;
            text-indent: 15px;
            border: none;
        }

        .buttonDownload:hover {
            background-color: #45a21a;
            color: white;
        }

        .buttonDownload:before, .buttonDownload:after {
            content: ' ';
            display: block;
            position: absolute;
            left: 15px;
            top: 52%;
        }

        .buttonDownload:before {
            width: 10px;
            height: 2px;
            border-style: solid;
            border-width: 0 2px 2px;
        }

        .buttonDownload:after {
            width: 0;
            height: 0;
            margin-left: 3px;
            margin-top: -7px;
            border-style: solid;
            border-width: 4px 4px 0 4px;
            border-color: transparent;
            border-top-color: inherit;
            animation: downloadArrow 1s linear infinite;
            animation-play-state: paused;
        }

        .buttonDownload:hover:before {
            border-color: #cdefbd;
        }

        .buttonDownload:hover:after {
            border-top-color: #cdefbd;
            animation-play-state: running;
        }

        @keyframes downloadArrow {
            0% {
                margin-top: -7px;
                opacity: 1;
            }

            0.001% {
                margin-top: -15px;
                opacity: 0.4;
            }

            50% {
                opacity: 1;
            }

            100% {
                margin-top: 0;
                opacity: 0.4;
            }
        }
    </style>



    <script>
        document.getElementById("applyButton").addEventListener("click", function() {
            var selectedYear = document.getElementById("cars").value;
            window.location.href = "/list?year=" + selectedYear;
        });
    </script>

    <script>
        document.getElementById("applyB").addEventListener("click", function() {
            var selectedOrder = document.getElementById("order").value;
            window.location.href = "/list?order=" + selectedOrder;
        });
    </script>










{% endblock %}

templates/admindash/affichMsg.html.twig
{% extends 'admindash/index.html.twig' %}

{% block title %}Messages index{% endblock %}

{% block body %}
 <div style="margin-top: 300px;">
    <h1>Messages index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Content</th>
                <th>Date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for message in messages %}
            <tr>
                <td>{{ message.content }}</td>
                <td>{{ message.date ? message.date|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('showmsg', {'id': message.id}) }}">show</a>
                    <a href="{{ path('mes_edit', {'id': message.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    </div>

    <a href="{{ path('mess_new') }}">Create new</a>


    <style>
    
    </style>
{% endblock %}

templates/admindash/affichRec.html.twig
{% extends 'admindash/index.html.twig' %}

{% block title %}Reclamation index{% endblock %}

{% block body %}
    <h1>Reclamation index</h1>



  <div style="margin-top: 300px">
    <table class="table">
        <thead>
            <tr>
                
                <th>DateRec</th>
                <th>Object</th>
                <th>Reclamation</th>
                <th>Email</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reclamation in reclamations %}
            <tr>
               
                <td>{{ reclamation.dateRec ? reclamation.dateRec|date('Y-m-d') : '' }}</td>
                <td>{{ reclamation.object }}</td>
                <td>{{ reclamation.reclamation }}</td>
                <td>{{ reclamation.email }}</td>
                <td>
                <a></a>
                    <a href="{{ path('reclamation_show', {'idRec': reclamation.idRec}) }}">show</a>
                    <a href="{{ path('Rec_Edit', {'idRec': reclamation.idRec}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>

    <a href="{{ path('Rec_new') }}">Create new</a>
{% endblock %}

templates/admindash/edit.html.twig
{% extends 'admindash/index.html.twig' %}

{% block title %}Edit Reclamation{% endblock %}

{% block body %}
    <h1>Edit Reclamation</h1>
     <div style="margin-top: 100px;">


    {{ include('admindash/_form.html.twig', {'button_label': 'Update'}) }}
        </div>

 <div style="margin-top: 50px;">

    <a href="{{ path('Rec') }}">back to list</a>
     <div style="margin-top: 50px;">


    {{ include('admindash/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/admindash/editM.html.twig
{% extends 'admindash/index.html.twig' %}

{% block title %}Edit Messages{% endblock %}

{% block body %}

    <h1>Edit Messages</h1>


    {{ include('admindash/M_form.html.twig', {'button_label': 'Update'}) }}  
       {{ include('admindash/M_delete.html.twig') }}


    <a href="{{ path('SASA') }}">back to list</a>

    </div>
{% endblock %}